name: Build Artifact

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-artifact:
    name: Build-Artifact-Rlib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build release
        run: cargo build --release --verbose

      - name: Upload rlib artifact
        uses: actions/upload-artifact@v4
        with:
          name: otplus-core-rlib
          path: target/release/deps/*.rlib
